### ISSUE TITLE
Homebrew installation instructions on the website should have you tap the tap instead of installing it

### ISSUE THREAD

**Issue by GameGamer43** [sniptt-official/snip#12]
The install instructions at https://www.sniptt.com/ have you  run `brew install sniptt-official/tap` which will fail with the error **Warning: No available formula or cask with the name "sniptt-official/tap"**. However if the instructions are updated to `brew tap sniptt-official/tap` the instructions work as expected.

**Comment by rickymarcon** [comment]
Oops...Nice catch @GameGamer43! We'll fix that now!

**Comment by rickymarcon** [comment]
Fix is live. Closing now 👍🏼 

Thanks again @GameGamer43!
